ASP.NET C# and MVC/MonsterDB/MonsterDB/Models/Monster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MonsterDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Monster
    {
        // NEED THIS TO MAKE YOUR OWN PRIMARY KEY VALUES
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Monster_ID { get; set; }
        [Required(ErrorMessage = "Monster needs a name"), StringLength(50, MinimumLength = 2)]
        public string Monster_Name { get; set; }
        [Required]
        public int Monster_HP { get; set; }
        [Required(ErrorMessage = "Monster needs to have a Race"), StringLength(10, MinimumLength = 1)]
        public string Monster_Race { get; set; }
        [Required(ErrorMessage = "Monster needs to have a property"), StringLength(10, MinimumLength = 1)]
        public string Monster_Property { get; set; }
    }

    // TODO change race and property from strings to enums

    /*
    public enum Monster_Race
    {
        Formless, Undead, Brute, Plant, Insect, Fish, Demon, Demi-Human, Angel, Dragon
    }
    */

    /*
    public enum Monster_Property
    {
        Neutral, Water, Earth, Fire, Wind, Poison, Holy, Shadow, Ghost, Undead
    }
    */
}

ASP.NET C# and MVC/MonsterDB/MonsterDB/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MonsterDB.Models;

namespace MonsterDB.Controllers
{
    public class ImportController : Controller
    {
        

        // GET: Import
        public ActionResult Index()
        {
            return View();
        }
    }
}

ASP.NET C# and MVC/MonsterDB/MonsterDB/Controllers/MonsterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MonsterDB.Models;
using MonsterDB.DAL;
using LinqToExcel;
using System.IO;
using System.Threading;
using ResumeParser;

namespace MonsterDB.Controllers
{
    public class MonsterController : Controller
    {
        // Original context to premade database
        //private MonDBEntities db = new MonDBEntities();

        private MonsterContext db = new MonsterContext();

        public ActionResult resume()
        {
            ResumeParse parser = new ResumeParse();

            var output = parser.Parse("C:\\Users\\EPS21\\Documents\\Tech-Academy-Projects\\ASP.NET C# and MVC\\MonsterDB\\MonsterDB\\resumes\\EricSheng_Resume.docx");
            //C:\Users\EPS21\Documents\Tech-Academy-Projects\ASP.NET C# and MVC\MonsterDB\MonsterDB\resumes\EricSheng_Resume.docx

            var FirstName = output.FirstName;
            ViewBag.fname = FirstName;

            //MiddleName = output.MiddleName;
            //LastName = output.LastName;
            //Gender = output.Gender;
            //EmailAddress = output.EmailAddress;
            //PhoneNumbers = output.PhoneNumbers;
            //Languages = output.Languages;
            //SummaryDescription = output.SummaryDescription;
            //Address1 = output.Address1;
            //Location = output.Location;
            //ZipCode = output.ZipCode;


            return View();
        }


        // GET Import
        public ActionResult Import()
        {
            return View();
        }

        // POST Import
        // The main import page to import a .xls or .xlsx Excel file
        // And add its rows to the monster database 
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase file)
        {
            // Currently only works with .xls files (xlxs if Excel is properly installed?)            
            if (file != null && file.ContentLength > 0 && 
               (file.FileName.EndsWith(".xls") || file.FileName.EndsWith(".xlsx")) )
            {
                // Getting file path of uploaded file with System.IO 
                string path = Path.Combine(Server.MapPath("~/App_Data/"),
                              Path.GetFileName(file.FileName));
                try
                {
                    /* Old file pathing            
                    string fileName = Path.GetFileName(file.FileName);
                    string targetPath = Server.MapPath("~/App_Data/");
                    file.SaveAs(targetPath + fileName);
                    string path = targetPath + fileName;
                    */
                    
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";

                    // LinqToExcel package to read Excel files
                    var excel = new ExcelQueryFactory();
                    excel.FileName = path;
                    var monsters = from x in excel.Worksheet<Monster>()
                                   select x;

                    // Iterating through read excel file and adding each row as a new monster
                    // into the monster database
                    foreach (var x in monsters)
                    {
                        Monster newMonster = new Monster();

                        newMonster.Monster_ID = x.Monster_ID;
                        newMonster.Monster_Name = x.Monster_Name;
                        newMonster.Monster_HP = x.Monster_HP;
                        newMonster.Monster_Race = x.Monster_Race;
                        newMonster.Monster_Property = x.Monster_Property;
                        db.Monsters.Add(newMonster);
                        db.SaveChanges();
                    }

                    // Delete the file from server after it has added entries to db
                    if (System.IO.File.Exists(path)) System.IO.File.Delete(path);
                    
                }
                catch (Exception ex)
                {
                    // If some other error, displays error message and deletes file from server
                    ViewBag.Message = "Error: " + ex.Message;
                    if (System.IO.File.Exists(path)) System.IO.File.Delete(path);
                    //return RedirectToAction("Index");
                }                

            }
            else if (file == null)
            {
                ViewBag.Message = "You have not specified a file";
            }
            else
            {
                ViewBag.Message = "Please input an Excel file";
            }
            
            //return RedirectToAction("Index");
            return View();
        }

        // GET: Monster
        /* Original Index method
        public ActionResult Index()
        {
            return View(db.Monsters.ToList());
        }
        */

        public ViewResult Index(string sortOrder, string searchString)
        {
            // Have sorting in columns controlled by hyperlink in column name
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.HPSortParm = sortOrder == "hp" ? "hp_desc" : "hp";
            ViewBag.RaceSortParm = sortOrder == "race" ? "race_desc" : "race";
            ViewBag.PropertySortParm = sortOrder == "prop" ? "prop_desc" : "prop";

            var monsters = from s in db.Monsters
                           select s;

            // If something is in the search string, search in Name, Property, and Race columns
            if (!String.IsNullOrEmpty(searchString))
            {
                monsters = monsters.Where(s => s.Monster_Name.Contains(searchString)
                                        || s.Monster_Property.Contains(searchString)
                                        || s.Monster_Race.Contains(searchString));
            }

            switch (sortOrder)
            {
                // Name Sort
                case "name_desc":
                    monsters = monsters.OrderByDescending(s => s.Monster_Name); break;
                case "name":
                    monsters = monsters.OrderBy(s => s.Monster_Name); break;

                // HP Sort
                case "hp_desc":
                    monsters = monsters.OrderByDescending(s => s.Monster_HP); break;
                case "hp":
                    monsters = monsters.OrderBy(s => s.Monster_HP); break;               

                // Race Sort
                case "race_desc":
                    monsters = monsters.OrderByDescending(s => s.Monster_Race); break;
                case "race":
                    monsters = monsters.OrderBy(s => s.Monster_Race); break;

                // Property Sort
                case "prop_desc":
                    monsters = monsters.OrderByDescending(s => s.Monster_Property); break;
                case "prop":
                    monsters = monsters.OrderBy(s => s.Monster_Property); break;

                // ID sort and default
                case "id_desc":
                    monsters = monsters.OrderByDescending(s => s.Monster_ID);
                    break;
                default:
                    monsters = monsters.OrderBy(s => s.Monster_ID);
                    break;
            }

            return View(monsters.ToList());
        }




        // GET: Monster/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monster monster = db.Monsters.Find(id);
            if (monster == null)
            {
                return HttpNotFound();
            }
            return View(monster);
        }

        // GET: Monster/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Monster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Monster_ID,Monster_Name,Monster_HP,Monster_Race,Monster_Property")] Monster monster)
        {
            if (ModelState.IsValid)
            {
                db.Monsters.Add(monster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(monster);
        }

        // GET: Monster/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monster monster = db.Monsters.Find(id);
            if (monster == null)
            {
                return HttpNotFound();
            }
            return View(monster);
        }

        // POST: Monster/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Monster_ID,Monster_Name,Monster_HP,Monster_Race,Monster_Property")] Monster monster)
        {
            if (ModelState.IsValid)
            {                
                db.Entry(monster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(monster);
        }

        // GET: Monster/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Create.cshtml
@model MonsterDB.Models.Monster

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Monster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Monster_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monster_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monster_ID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Monster_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monster_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monster_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monster_HP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monster_HP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monster_HP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monster_Race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monster_Race, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monster_Race, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monster_Property, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monster_Property, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monster_Property, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Delete.cshtml
@model MonsterDB.Models.Monster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Monster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Monster_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_HP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_HP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Property)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Property)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Details.cshtml
@model MonsterDB.Models.Monster

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Monster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Monster_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_HP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_HP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monster_Property)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monster_Property)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Monster_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Edit.cshtml
@model MonsterDB.Models.Monster

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Monster</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Monster_ID)
    

    <!-- Trying to be able to edit Monster_ID but doesn't work. The HiddenFor above is protecting it from being edited, if
        edited it will have an error
    <div class="form-group">
        @Html.LabelFor(model => model.Monster_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Monster_ID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Monster_ID, "", new { @class = "text-danger" })
        </div>
    </div>
    -->

    <div class="form-group">
        @Html.LabelFor(model => model.Monster_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Monster_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Monster_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Monster_HP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Monster_HP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Monster_HP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Monster_Race, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Monster_Race, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Monster_Race, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Monster_Property, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Monster_Property, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Monster_Property, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Import.cshtml
@*@model MonsterDB.Models.Monster*@

@{
    ViewBag.Title = "Import";
}



<h2>Import</h2>
<h4>Add Monsters via Excel</h4>

@using (Html.BeginForm("Import", "Monster", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
<div class="form-horizontal">

    <div class="form-group">
        <input type="file" id="file" name="file" class="" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload Excel File" id="SubmitBtn" class="btn-primary" />
    </div>

    @{
        if (ViewBag.Message == "File uploaded successfully")
        {
            @ViewBag.Message
            <meta http-equiv="refresh" content="3; 'Index'" />
        }
        else
        {
            @ViewBag.Message
        }
    }    

</div>

}

    

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/Index.cshtml
@model IEnumerable<MonsterDB.Models.Monster>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Search Monsters: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Monster ID", "Index", new { sortOrder = ViewBag.IdSortParm })
        </th>
        <th>
            @Html.ActionLink("Monster Name", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @Html.ActionLink("Monster HP", "Index", new { sortOrder = ViewBag.HPSortParm })
        </th>
        <th>
            @Html.ActionLink("Monster Race", "Index", new { sortOrder = ViewBag.RaceSortParm })
        </th>
        <th>
            @Html.ActionLink("Monster Property", "Index", new { sortOrder = ViewBag.PropertySortParm })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Monster_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monster_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monster_HP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monster_Race)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monster_Property)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Monster_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.Monster_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Monster_ID })
            </td>
        </tr>
    }

</table>

ASP.NET C# and MVC/MonsterDB/MonsterDB/Views/Monster/resume.cshtml
@{
    ViewBag.Title = "resume";
}

<h2>resume</h2>
<p>@ViewBag.fname</p>